### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by lclc** [tomasvdw/bitcrust#2]
By law (afaik) every code that doesn't have a license is by default closed source.

Also, regarding using the consensus code from Bitcoin Core:
the libbitcoin project / @evoskuil has made a nice library from the core code with only the 33 files that are considered to be bitcoin script consensus-critical from bitcoin-core 0.14.0. Maybe you'd like to use it too: https://github.com/libbitcoin/libbitcoin-consensus

Cool project! :)

**Comment by lclc** [comment]
https://choosealicense.com/ might be a good starting point.

Most Bitcoin project seem to use the MIT License.

**Comment by tomasvdw** [comment]
I have added the MIT license,

Thanks.
